"""Generated from SOP_OCR_Anh_NhatTrinh_MMTB_V1.1.docx. Do not edit aliases ad hoc."""

STATUS_ALIASES: dict[str, tuple[str, ...]] = {'Máy nghỉ': ('máy nghỉ', 'xe nghỉ', 'nghỉ off'),
 'Mưa nghỉ / Không thi công do mưa': ('mưa nghỉ',
                                      'nghỉ mưa',
                                      'trời mưa nghỉ',
                                      'BCH/kỹ thuật báo nghỉ',
                                      'đất ướt/ẩm không lu được',
                                      'chờ việc do mưa'),
 'Máy hỏng / Sửa chữa': ('máy hỏng',
                         'xe hỏng',
                         'sửa máy',
                         'sửa chữa máy',
                         'máy hỏng chờ sửa chữa',
                         'nghỉ sửa máy'),
 'Chờ việc': ('chờ việc', 'chờ việc do mưa'),
 'Chờ dầu': ('chờ dầu',),
 'Chờ bàn giao / Trả máy': ('chờ bàn giao máy', 'trả máy NCC'),
 'Trực sản xuất': ('trực sản xuất', 'trời mưa trực sản xuất', 'trực sản xuất do trời mưa'),
 'Nghỉ bảo dưỡng': ('nghỉ bảo dưỡng máy',)}

JOB_ALIASES: dict[str, tuple[str, ...]] = {'Dọn vệ sinh': ('dọn vệ sinh', 'dọn vệ sinh bãi đúc', 'dọn vệ sinh đường'),
 'Dọn rác': ('dọn rác', 'xử lý dọn rác', 'dọn trạc', 'xúc dọn trạc rác'),
 'Gắp rác': ('gắp rác',),
 'Chở rác': ('chở rác', 'vc rác', 'vận chuyển rác', 'chạy rác', 'rác chạc'),
 'Dọn cỏ / Phát quang': ('dọn cỏ', 'cào dọn cỏ', 'phát quang'),
 'Vận chuyển vật tư': ('vc vật tư',
                       'chuyển vật tư',
                       'chở vật tư',
                       'vận chuyển vật tư',
                       'cẩu chuyển vật tư khi ngữ cảnh là vận chuyển'),
 'Vận chuyển đất': ('vận chuyển đất', 'vc đất', 'chở đất', 'chuyển đất'),
 'Vận chuyển cát': ('vc cát', 'chở cát', 'chuyển cát'),
 'Vận chuyển đá': ('vc đá', 'chở đá'),
 'Vận chuyển base': ('vận chuyển base', 'chuyển base'),
 'Vận chuyển bùn': ('vc bùn', 'chở bùn'),
 'Vận chuyển cống': ('vc cống', 'chuyển cống', 'cẩu chuyển cống'),
 'Chuyển tải': ('chuyển tải', 'xúc đất chuyển tải', 'chuyển tải đất'),
 'Xúc đất': ('xúc đất', 'múc đất', 'xúc đất màu', 'xúc đất đá'),
 'Xúc đất lên xe': ('xúc đất lên ô tô', 'xúc đất lên xe', 'xúc xe khi ngữ cảnh là xúc đất', 'xúc đất xe ben'),
 'Xúc cát': ('xúc cát', 'xúc cát lên xe', 'xúc cát đổ mang cống'),
 'Xúc base': ('xúc base',),
 'Xúc bùn': ('xúc bùn', 'múc bùn', 'vét bùn khi thao tác xúc bùn'),
 'Xúc đá': ('xúc đá',),
 'Xúc vật liệu': ('xúc vật liệu', 'chỉ dùng khi không xác định được đất/cát/đá/base'),
 'Xúc bê tông / phế thải': ('xúc bê tông', 'xúc trạc', 'xúc xỉ'),
 'Quăng đất': ('quăng đất', 'quăng đất vào móng', 'quăng đất làm mái', 'xúc quăng đất'),
 'Quăng cát': ('quăng cát', 'quăng tải cát'),
 'Quăng bùn': ('quăng bùn', 'quăng tải bùn', 'xúc quăng bùn'),
 'Gom đất': ('gom đất',),
 'Gom cát': ('gom cát', 'vun cát', 'xúc cát vun đống'),
 'Gom base': ('gom base',),
 'San mặt bằng': ('san mặt bằng', 'san gạt mặt bằng', 'san đất mặt bằng', 'dọn san mặt bằng', 'làm mặt bằng'),
 'San đất / San nền': ('san đất', 'san nền', 'xúc đất san nền', 'san gạt khi ngữ cảnh là nền đất'),
 'San cát': ('san cát', 'sang cát/sàng cát chỉ map khi thực tế là san, nếu đúng nghĩa sàng thì giữ NEW_JOB'),
 'San base': ('san base', 'cào base', 'nền base'),
 'San lấp': ('san lấp', 'san lấp mặt bằng', 'san lấp nền'),
 'San lề': ('san lề', 'san lề vỉa hè', 'san bây/san lề'),
 'San vỉa hè': ('san vỉa hè', 'san vỉa'),
 'San sửa đường': ('san sửa đường', 'gạt đường'),
 'Xử lý nền': ('xử lý nền',),
 'Xử lý cao su': ('xử lý cao su', 'xử lý cao su mặt đường'),
 'Đắp lề': ('đắp lề', 'đắp lề đường', 'đắp dọn lề', 'làm lề đường'),
 'Đắp bờ': ('đắp bờ', 'đắp bờ mương hở', 'đắp bờ chắn bùn'),
 'Đắp khuôn đường': ('đắp khuôn đường', 'xúc đất đắp khuôn đường'),
 'Đắp vuốt khuôn / lề': ('đắp vuốt khuôn đường', 'đắp vuốt khuôn lề'),
 'Lu đường': ('lu đường', 'lu nền đường'),
 'Lu nền': ('lu nền', 'lu đất'),
 'Lu base': ('lu base',),
 'Lu cát': ('lu cát', 'lu cát nền base', 'lu cát vườn ươm'),
 'Đào móng': ('đào móng', 'đào đất móng', 'đào đất hố móng', 'đào móng đài', 'đào móng nền dầm'),
 'Đào móng đầu cọc': ('đào móng đầu cọc',),
 'Đào móng hàng rào': ('đào móng hàng rào', 'đào hố chôn cọc hàng rào'),
 'Đào hố': ('đào hố',),
 'Đào hố ép cọc': ('đào hố ép cọc',),
 'Đào hố ga': ('đào hố ga', 'đào đặt hố ga', 'đào hạ ga'),
 'Đào rãnh thoát nước': ('đào rãnh thoát nước', 'đào rãnh thóa nước', 'khơi rãnh thoát nước'),
 'Đào mương thoát nước': ('đào mương thoát nước', 'đào mương', 'đào mương hở'),
 'Đào đường điện': ('đào đường điện', 'đào hạ đường điện', 'đào thu hồi đường điện'),
 'Đào gen điện': ('đào gen điện', 'đào lấp gen điện', 'đào hạ gen điện', 'đào hạ đèn/lấp gen'),
 'Đào đường ống điện': ('đào đường ống điện', 'đào ống điện', 'đào lắp ống điện', 'đào ống sun điện'),
 'Đào đường ống nước': ('đào ống nước', 'đào lấp ống nước', 'đào hạ ống nước'),
 'Đào cống / khuôn cống': ('đào cống', 'đào khuôn cống', 'đào khuôn hạ cống', 'đào cống hộp'),
 'Đào khuôn đường': ('đào khuôn đường', 'đào khuôn', 'cào khuôn khi ngữ cảnh là tạo khuôn đường'),
 'Đào khuôn vỉa hè': ('đào khuôn vỉa hè',),
 'Đào hàng rào': ('đào hàng rào', 'đào lắp đặt hàng rào'),
 'Đào đế/cột đèn': ('đào đế đèn',
                    'đào đặt đế đèn',
                    'đào hạ đế đèn',
                    'đào hạ đế cột',
                    'đào dựng đèn chiếu sáng'),
 'Đào bể': ('đào bể nước', 'đào bể'),
 'Lấp móng': ('lấp móng', 'san gạt lấp móng', 'san lấp móng'),
 'Lấp cống': ('lấp cống', 'đào lấp cống', 'san lấp cống'),
 'Lấp đường điện / gen điện': ('lấp đường điện', 'đào lấp đường điện', 'lấp gen điện', 'lấp dây đèn'),
 'Lấp ống nước / ống điện': ('lấp ống nước', 'lấp ống điện', 'đào lấp ống HDPE'),
 'Lấp hố ga / bể': ('lấp hố ga', 'lấp bể', 'san lấp bể thoát nước'),
 'Hoàn trả mặt bằng': ('trả mặt bằng', 'lấp trả mặt bằng', 'san trả mặt bằng', 'san lấp hoàn trả mặt bằng'),
 'Cẩu vật tư': ('cẩu vật tư', 'cẩu vt', 'cẩu đồ', 'cẩu vật liệu'),
 'Cẩu cống': ('cẩu cống', 'cẩu hạ cống', 'gắp cống'),
 'Cẩu hố ga / ga': ('cẩu hố ga', 'cẩu ga', 'cẩu hạ ga'),
 'Cẩu tấm đan': ('cẩu tấm đan', 'gắp tấm đan', 'chuyển tấm đan'),
 'Cẩu cốt pha': ('cẩu cốt pha', 'cảu cốt pha'),
 'Cẩu cáp': ('cẩu cáp',),
 'Cẩu ống': ('cẩu ống', 'cẩu ống nước', 'cẩu ống sun điện'),
 'Cẩu đế/cột đèn': ('cẩu đế đèn', 'cẩu cột', 'nâng hạ cột đèn'),
 'Cẩu vải địa': ('cẩu vải địa', 'cẩu hạ vải địa'),
 'Cẩu bó vỉa': ('cẩu bó vỉa',),
 'Cẩu máy phát': ('cẩu máy phát',),
 'Cẩu sắt / thép': ('cẩu sắt',),
 'Cẩu gạch / xi măng': ('cẩu gạch', 'cẩu xi'),
 'Đặt cống': ('đặt cống', 'đào đặt cống', 'đào lắp cống', 'lắp cống'),
 'Hạ cống': ('hạ cống', 'cẩu hạ cống', 'đào hạ cống'),
 'Đặt hố ga / ga': ('đặt hố ga', 'đặt ga', 'hạ đặt ga'),
 'Hạ ga': ('hạ ga', 'hạ hố ga', 'đào hạ ga'),
 'Đậy nắp ga': ('đậy nắp ga', 'đậy nắp hố ga', 'cẩu đậy nắp ga'),
 'Đậy nắp tấm đan': ('đậy nắp tấm đan',),
 'Dựng cột đèn': ('dựng cột đèn', 'đặt cột đèn', 'dựng đèn chiếu sáng'),
 'Đặt đế đèn': ('đặt đế đèn', 'hạ đế đèn', 'nâng hạ đế đèn'),
 'Sửa cột đèn': ('sửa cột đèn', 'dựng sửa cột đèn', 'nâng sửa cột đèn'),
 'Sửa đế đèn': ('sửa đế đèn', 'nâng sửa đế đèn', 'sửa đế cột đèn'),
 'Sửa đèn chiếu sáng': ('sửa đèn', 'sửa chữa bóng đèn', 'sửa đèn chiếu sáng'),
 'Kéo cáp': ('kéo cáp', 'kéo cáp điện'),
 'Thu hồi đường điện': ('thu hồi đường điện', 'thu hồi đường điện tạm', 'thu hồi đường sun và cáp điện'),
 'Thu hồi đèn/dây điện tạm': ('thu hồi đèn tạm', 'dây điện tạm'),
 'Đóng cọc tiếp địa': ('đóng cọc tiếp địa', 'đóng cọc tiếp điện'),
 'Đổ bê tông': ('đổ bê tông', 'dổ bê tông', 'đổ bê tông ga', 'đổ nắp cống hộp'),
 'Đục phá bê tông': ('đục phá bê tông', 'bắn phá bê tông', 'đục bê tông', 'phá dỡ bê tông'),
 'Đục đầu cọc': ('đục đầu cọc', 'đục bê tông đầu cọc', 'đục cọc'),
 'Đục cọc khoan nhồi': ('đục cọc khoan nhồi',),
 'Bảo dưỡng bê tông': ('bảo dưỡng bê tông',),
 'Làm cốt nền / cốt bê tông': ('làm cốt nền', 'làm nền cốt', 'làm nền cốt bê tông', 'làm cốt nền lót'),
 'Lắp/cẩu cọc bê tông': ('lắp đặt cẩu cọc bê tông', 'cẩu cột bê tông'),
 'Làm taluy / mái mương': ('làm taluy mương hở', 'làm mái mương hở', 'xử lý mái'),
 'Kè đá': ('kè đá',),
 'Nạo vét bờ kè': ('nạo vét bờ kè', 'nạo vết bờ kè'),
 'Tạo/khơi rãnh thoát nước': ('tạo rãnh thoát nước', 'khơi nước', 'khơi thoát nước', 'khai rãnh'),
 'Đóng cọc tre': ('đóng cọc tre',),
 'Trồng cây': ('trồng cây',),
 'Làm hàng rào': ('làm hàng rào', 'lắp đặt hàng rào'),
 'Phục vụ thảm nhựa': ('phục vụ công tác thảm nhựa',),
 'Cấp nước': ('cấp nước',),
 'Tưới/Rửa đường': ('rửa đường', 'tưới nước rửa đường', 'cấp nước rửa đường', 'đong nước rửa đường'),
 'Dập bụi': ('dập bụi',),
 'Rửa xe': ('rửa xe',),
 'Rửa đá': ('rửa đá',),
 'Bơm/Tát nước': ('bơm nước', 'tát nước', 'múc nước')}
