<?php
namespace App\Services;
use App\Models\{ActivityLog,Machine,OcrJob,User};use Illuminate\Contracts\Pagination\LengthAwarePaginator;use Illuminate\Database\Eloquent\Builder;use Illuminate\Support\Collection;use Illuminate\Support\Facades\{DB,Storage};
class OcrReviewService{
public function paginate(array $f):LengthAwarePaginator{return OcrJob::with(['machine:id,asset_code','attachment.message'])->when($f['q']??null,function(Builder $q,string $v){$s='%'.trim($v).'%';$q->where(fn($n)=>$n->where('asset_code','like',$s)->orWhereHas('attachment.message',fn($m)=>$m->where('message_id','like',$s)->orWhere('sender_name','like',$s)));})->when($f['status']??null,fn($q,$v)=>$q->where('status',$v))->when($f['review_status']??null,fn($q,$v)=>$q->where('review_status',$v))->when($f['document_type']??null,fn($q,$v)=>$q->where('document_type',$v))->when($f['machine_id']??null,fn($q,$v)=>$q->where('machine_id',$v))->orderByRaw("CASE review_status WHEN 'PENDING' THEN 0 WHEN 'REJECTED' THEN 1 ELSE 2 END")->latest('id')->paginate(30)->withQueryString();}
public function statusCounts():Collection{return OcrJob::selectRaw('status,COUNT(*) total')->groupBy('status')->pluck('total','status');}
public function reviewStatusCounts():Collection{return OcrJob::selectRaw('review_status,COUNT(*) total')->groupBy('review_status')->pluck('total','review_status');}
public function dailyOverview(string $date):Collection{return OcrJob::with('machine:id,asset_code')->where('document_type','DAILY_TIMEMARK')->whereDate('extracted_date',$date)->get()->groupBy(fn($j)=>($j->machine_id?:'unknown').'|'.$j->extracted_date?->format('Y-m-d'))->map(function($jobs){$j=$jobs->first();return['machine'=>$j->machine?->asset_code?:$j->asset_code?:'Chưa xác định','date'=>$j->extracted_date?->format('d/m/Y'),'total'=>$jobs->count(),'pending'=>$jobs->where('review_status','PENDING')->count(),'exceptions'=>$jobs->where('status','EXCEPTION')->count()];})->values();}
public function machineOptions():Collection{return Machine::orderBy('asset_code')->get(['id','asset_code']);}
public function detail(OcrJob $j):OcrJob{return $j->load(['machine','attachment.message','journalDocument.rows','reviewer:id,name','activities.user:id,name']);}
public function imageExists(OcrJob $j):bool{return $j->attachment&&Storage::disk($j->attachment->storage_disk)->exists($j->attachment->storage_path);}
public function review(OcrJob $j,array $d,User $u):OcrJob{return DB::transaction(function()use($j,$d,$u){$before=$j->only(['status','review_status','machine_id','asset_code','extracted_date','extracted_time','exceptions']);$a=$d['action'];$x=['review_status'=>match($a){'approve'=>'APPROVED','correct'=>'CORRECTED','reject'=>'REJECTED'},'reviewed_by'=>$u->id,'reviewed_at'=>now(),'review_notes'=>$d['review_notes']??null];if($a==='correct'){$m=Machine::findOrFail($d['machine_id']);$x+=['machine_id'=>$m->id,'asset_code'=>$m->asset_code,'extracted_date'=>$d['extracted_date']??$j->extracted_date,'extracted_time'=>$d['extracted_time']??$j->extracted_time,'operator_name'=>$d['operator_name']??$j->operator_name,'phone'=>$d['phone']??$j->phone,'work_location'=>$d['work_location']??$j->work_location,'status'=>'COMPLETED','exceptions'=>null];}$j->update($x);ActivityLog::create(['user_id'=>$u->id,'machine_id'=>$j->machine_id,'event'=>'ocr.reviewed','description'=>"Hậu kiểm OCR job #{$j->id}: {$a}",'subject_type'=>OcrJob::class,'subject_id'=>$j->id,'properties'=>['action'=>$a,'before'=>$before,'after'=>$j->fresh()->only(array_keys($before))],'occurred_at'=>now()]);return$j->fresh();});}
public function bulkReview(array $d,User $u):int{$n=0;foreach(OcrJob::whereIn('id',$d['job_ids'])->get()as$j){$this->review($j,['action'=>$d['action'],'review_notes'=>$d['review_notes']??null],$u);$n++;}return$n;}
public function exceptionLabels():array{return['LOW_CONFIDENCE'=>'Độ tin cậy thấp','MISSING_DATE'=>'Thiếu ngày','MISSING_TIME'=>'Thiếu giờ','UNKNOWN_ASSET_CODE'=>'Mã máy không tồn tại','WRONG_DATE'=>'Sai ngày gửi','JOURNAL_ROW_EXCEPTION'=>'Dòng nhật trình cần kiểm tra'];}}